language: node_js

node_js:
  - "8"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/serenity-sync-server/node_modules
    - packages/serenity-sync-web/node_modules

install: travis/install.sh
before_script: travis/before_script.sh
script: travis/script.sh
after_script: travis/after_script.sh
